services:
  prometheus:
    image: prom/prometheus:v3.8.0
    container_name: prometheus_server_robust6g
    profiles: ["aggregation_module.prometheus"]
    depends_on:
      - discovery-agent
    environment:
      - TZ=UTC
    volumes:
      - ${PFD}/Aggregation_Normalisation_Module/Configuration_Files/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ${PFD}/Aggregation_Normalisation_Module/Configuration_Files/rules:/etc/prometheus/rules:ro
      - ${PFD}/Results/prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    restart: unless-stopped

  discovery-agent:
    image: discovery_agent_robust6g:latest
    build:
      context: ${PFD}
      dockerfile: Aggregation_Normalisation_Module/Docker/Dockerfiles/discovery_agent.dockerfile
    container_name: discovery_agent_robust6g
    profiles: ["aggregation_module.prometheus"] #Same profile because Prometheus needs this microservice
    environment:
      - SCAN_PORT="9999"
      - SCAN_TIMEOUT="0.2"
      - TZ=UTC
    network_mode: "${NETWORK_MODE}"
    volumes:
      - ${PFD}/Aggregation_Normalisation_Module/Scripts:/opt/discovery
    restart: unless-stopped

volumes:
  prometheus_data: