# sudo docker compose up -d
# sudo docker exec -it IDCONTAINER bash
---
services:
  alert_module:
    image: alert_module_robust6g:latest
    build:
      context: ${PFD}
      dockerfile: Alert_Module/Docker/Dockerfiles/alert_module.dockerfile
    container_name: alert_module_robust6g
    profiles: ["alert_module.alert_module"]
    depends_on:
      kafka_robust6g:
        condition: service_healthy
    environment:
      - TZ=${TZ}
      - KAFKA_BOOTSTRAP=${KAFKA_BOOTSTRAP}
      - SNORT_KAFKA_GROUP_ID={SNORT_KAFKA_GROUP_ID}
      - SNORT_KAFKA_TOPIC_IN=${SNORT_KAFKA_TOPIC_IN}
      - SNORT_KAFKA_TOPIC_OUT=${SNORT_KAFKA_TOPIC_OUT}
      - SNORT_ALERT_TAP_IFACE=${SNORT_ALERT_TAP_IFACE}
      - MONGO_URI=${MONGO_URI}
      - SNORT_KAFKA_MESSAGE_FIELD=${SNORT_KAFKA_MESSAGE_FIELD}
      - SNORT_CONSUMER_KAFKA_AUTO_OFFSET_RESET=${SNORT_CONSUMER_KAFKA_AUTO_OFFSET_RESET}
      - SNORT_CONSUMER_KAFKA_ENABLE_AUTO_COMMIT=${SNORT_CONSUMER_KAFKA_ENABLE_AUTO_COMMIT}
      - SNORT_CONSUMER_KAFKA_PARTITION_ASSIGNMENT_STRATEGY=${SNORT_CONSUMER_KAFKA_PARTITION_ASSIGNMENT_STRATEGY}
      - SNORT_CONSUMER_KAFKA_ENABLE_PARTITION_EOF=${SNORT_CONSUMER_KAFKA_ENABLE_PARTITION_EOF}
      - SNORT_CONSUMER_KAFKA_ALLOW_AUTO_CREATE_TOPICS=${SNORT_CONSUMER_KAFKA_ALLOW_AUTO_CREATE_TOPICS}
      - SNORT_CONSUMER_FETCH_MIN_BYTES=${SNORT_CONSUMER_FETCH_MIN_BYTES}
      - SNORT_CONSUMER_FETCH_WAIT_MAX_MS=${SNORT_CONSUMER_FETCH_WAIT_MAX_MS}
      - SNORT_CONSUMER_QUEUED_MAX_MESSAGES_KBYTES=${SNORT_CONSUMER_QUEUED_MAX_MESSAGES_KBYTES}
      - SNORT_CONSUMER_MAX_POLL_INTERVAL_MS=${SNORT_CONSUMER_MAX_POLL_INTERVAL_MS}
      - SNORT_CONSUMER_SESSION_TIMEOUT_MS=${SNORT_CONSUMER_SESSION_TIMEOUT_MS}
      - SNORT_PRODUCER_KAFKA_PRODUCER_LINGER_MS=${SNORT_PRODUCER_KAFKA_PRODUCER_LINGER_MS}
      - SNORT_PRODUCER_BATCH_NUM_MESSAGES=${SNORT_PRODUCER_BATCH_NUM_MESSAGES}
      - SNORT_PRODUCER_KAFKA_PRODUCER_BATCH_SIZE=${SNORT_PRODUCER_KAFKA_PRODUCER_BATCH_SIZE}
      - SNORT_PRODUCER_KAFKA_PRODUCER_COMPRESSION=${SNORT_PRODUCER_KAFKA_PRODUCER_COMPRESSION}
    # If host.docker.internal is used in Linux:
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${KAFKA_LAN_HOSTNAME}:host-gateway"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${PFD}/Results/Alerts:/home/Alert_Module/Alerts
    restart: unless-stopped
