---
services:
  thingsboard_collector:
    image: thingsboard_collector_robust6g:latest
    build:
      context: ${PFD}
      dockerfile: ThingsBoard_Collector_Module/Docker/Dockerfiles/thingsboard_collector.dockerfile
    container_name: thingsboard_collector_robust6g
    profiles: ["thingsboard_module.alarm_collector"]
    network_mode: "host" #Network_mode with bridge needs the port mapping
    depends_on:
      kafka_robust6g:
        condition: service_healthy
    environment:
      - TZ=UTC
      - KAFKA_BOOTSTRAP=${KAFKA_BOOTSTRAP}
      - TB_USERNAME=${TB_USERNAME}
      - TB_PASSWORD=${TB_PASSWORD}
      - TB_USE_HTTPS=${TB_USE_HTTPS}  # Set to true if ThingsBoard uses HTTPS
    restart: unless-stopped
