#Just in case of debug
#<system>
  #log_level debug
#</system>

# Sources
<source>
  @type systemd
  @id source_systemd
  path /var/log/journal
  <storage>
    @type local
    persistent true
    path /fluentd/log/fluentd-journal-pos.json
  </storage>
  <entry>
    fields_strip_underscores true
    fields_lowercase true
  </entry>
  tag systemd
</source>

<source>
  @type tail
  @id source_syslog
  path /var/log/syslog
  pos_file /fluentd/log/fluentd-syslog.pos
  tag syslog
  format syslog
</source>

# Expose metrics to Prometheus
<source>
  @type prometheus
  @id source_prometheus
  bind 0.0.0.0
  port 24231
</source>

# Fluentd internal metrics
<source>
  @type monitor_agent
  @id source_in_monitor_agent
  tag internal_metrics_fluentd
  bind 0.0.0.0
  port 24220
  emit_interval 20
</source>

# Filter for systemd data formatting
<filter systemd>
  @type record_transformer
  enable_ruby true
  renew_record true
  keep_keys priority,syslog_facility,syslog_identifier,job_type,job_result,message,pid,uid,gid,comm,exe,cmdline,unit
  <record>
    machine_id      "#{ENV['MACHINE_ID']}"
    priority        ${record["priority"]}
    facility        ${record["syslog_facility"]}
    identifier      ${record["syslog_identifier"]}
    job_type        ${record["job_type"]}
    job_result      ${record["job_result"]}
    message         ${record["message"]}
    pid             ${record["pid"]}
    uid             ${record["uid"]}
    gid             ${record["gid"]}
    comm            ${record["comm"]}
    exe             ${record["exe"]}
    cmdline         ${record["cmdline"]}
    unit            ${record["unit"]}
  </record>
</filter>

# Filter for sysslog data formatting
<filter syslog>
  @type record_transformer
  enable_ruby true
  <record>
    machine_id "#{ENV['MACHINE_ID']}"
  </record>
</filter>

# Prometheus log processing metrics
<match internal_metrics_fluentd>
  @type prometheus
  @id match_metric_agent_to_prometheus

  <metric>
    name fluentd_output_status_buffer_queue_length
    type gauge
    desc length of the buffer queue for outputs
    key buffer_queue_length
  </metric>

  <metric>
    name fluentd_output_status_retry_count
    type counter
    desc number of output retries
    key retry_count
  </metric>

  <metric>
    name fluentd_buffer_total_queued_size
    type gauge
    desc total queue size in bytes
    key buffer_total_queued_size
  </metric>
</match>


# Output file management
<match systemd>
  @type file
  path /fluentd/log/out/systemd_output.log
  append true
  <buffer>
    flush_mode interval
    flush_interval 20s
  </buffer>
</match>

<match syslog>
  @type file
  @id match_syslog_to_stdout
  path /fluentd/log/out/syslog_output.log
  append  true
  <buffer>
    flush_mode interval
    flush_interval 20s
  </buffer>
</match>
