input {
  kafka {
    bootstrap_servers => "kafka_robust6g-node1.lan:9094"
    topics => ["syslog_logs", "systemd_logs", "falco_events", "telegraf_metrics"]
    codec => "json"
    auto_offset_reset => "latest"
    group_id => "logstash_ingestor"
    decorate_events => true 
  }
}

filter {

  if ! [kafka_topic] {
    mutate { add_field => { "kafka_topic" => "%{[@metadata][kafka][topic]}" } }
  }

  # Fluentd
  if [kafka_topic] in ["syslog_logs", "systemd_logs"] {
    grok {
      match => { "message" => "[^{]*(?<json_payload>\{.*)" }
    }

    json {
      source => "json_payload"
      target => "tmp_json_data"
      remove_field => ["json_payload", "message"] 
    }

    mutate {
      rename => { "[tmp_json_data][machine_id]" => "[host][id]" }
      rename => { "[tmp_json_data][host]" => "syslog_hostname" }
      rename => { "[tmp_json_data][message]" => "syslog_message" }
      rename => { "[tmp_json_data][priority]" => "syslog_priority" }
      rename => { "[tmp_json_data][syslog_identifier]" => "syslog_identifier" }
      rename => { "[tmp_json_data][pid]" => "[process][pid]" }
      rename => { "[tmp_json_data][comm]" => "[process][name]" }
    }
    
    mutate { remove_field => ["tmp_json_data"] }

    mutate {
      add_field => { "[event][module]" => "system" }
      add_field => { "[event][dataset]" => "%{kafka_topic}" }
    }
  }

  # Falco
  else if [kafka_topic] == "falco_events" {
    json {
      source => "message"
      target => "tmp_falco"
    }

    mutate {
      rename => { "[tmp_falco][output_fields][machine_id]" => "[host][id]" }
      rename => { "[tmp_falco][hostname]" => "falco_hostname" }
    }
    
    ruby {
        code => '
            event.get("tmp_falco").each do |k, v|
                event.set(k, v) unless k == "hostname"
            end
        '
    }
    mutate { remove_field => ["tmp_falco", "message", "hostname"] }

    mutate {
      add_field => { "[event][module]" => "falco" }
      add_field => { "[event][dataset]" => "alert" }
    }
  }

  # Telegraf
  else if [kafka_topic] == "telegraf_metrics" {
    
    if [event][original] {
        json {
            source => "[event][original]"
            target => "telegraf_clean_data"
        }
    }
    
    mutate {
        rename => { "[telegraf_clean_data][tags][machine_id]" => "[host][id]" }
        rename => { "[telegraf_clean_data][tags][host]" => "[host][name]" }
        rename => { "[telegraf_clean_data][name]" => "[event][dataset]" }
    }

    mutate {
        rename => { "[telegraf_clean_data][tags]" => "telegraf_tags" }
    }

    mutate {
        remove_field => ["telegraf_clean_data", "_tags", "tags", "_tagsparsefailure"]
        add_field => { "[event][module]" => "telegraf" }
    }
  }

--
  date {
    match => [ "timestamp", "ISO8601", "UNIX", "UNIX_MS" ]
    target => "@timestamp"
  }
}

output {
  opensearch {
    hosts => ["https://${OPENSEARCH_HOST}:9200"]
    index => "logs-%{kafka_topic}-%{+YYYY.MM.dd}"
    user => "admin"
    password => "${OPENSEARCH_PASSWORD}"
    ssl => true
    ssl_certificate_verification => false
  }
}