input {
  kafka {
    bootstrap_servers => "kafka_robust6g-node1.lan:9094"
    topics => ["syslog_logs", "systemd_logs", "falco_events", "telegraf_metrics"]
    codec => "plain"
    auto_offset_reset => "latest"
    group_id => "logstash_ingestor"
    decorate_events => true 
  }
}

# FIXME Ajustar filter para que coja bien el machine_id porque lo mete en el campo message siempre
filter {
  # For all normalized logs
  mutate {
    add_field => { "kafka_topic" => "%{[@metadata][kafka][topic]}" }
  }

  # Fluentd
  if [kafka_topic] in ["syslog_logs", "systemd_logs"] {
    mutate {
      add_field => { "[event][kind]" => "event" }
      add_field => { "[event][module]" => "system" }
      add_field => { "[event][dataset]" => "%{kafka_topic}" }
    }
    if [message] =~ "^\{" {
        json { source => "message" }
    } else {
        dissect {
            mapping => {
                "message" => "%{ts} %{tag} %{json_payload}"
            }
        }
        if [json_payload] {
            json { source => "json_payload" remove_field => ["json_payload", "message"] }
        }
    }
    
    if [machine_id] {
      mutate { rename => { "machine_id" => "[host][id]" } }
    }
  }

  # Falco
  else if [kafka_topic] == "falco_events" {
    json { source => "message" }

    mutate {
      add_field => { "[event][kind]" => "alert" }
      add_field => { "[event][category]" => "intrusion_detection" }
      add_field => { "[event][dataset]" => "falco" }
    }

    if [output_fields][machine_id] {
      mutate { rename => { "[output_fields][machine_id]" => "[host][id]" } }
    }
    else if [machine_id] {
      mutate { rename => { "machine_id" => "[host][id]" } }
    }

    if [priority] == "Critical" { mutate { add_field => { "[event][severity]" => 50 } } }
    else if [priority] == "Error" { mutate { add_field => { "[event][severity]" => 40 } } }
    else if [priority] == "Warning" { mutate { add_field => { "[event][severity]" => 30 } } }
    else if [priority] == "Notice" { mutate { add_field => { "[event][severity]" => 20 } } }
    else { mutate { add_field => { "[event][severity]" => 10 } } }
  }

  # Telegraf
  else if [kafka_topic] == "telegraf_metrics" {
    json { source => "message" }

    mutate {
      add_field => { "[event][kind]" => "metric" }
      add_field => { "[event][module]" => "telegraf" }
    }
    
    if [name] {
      mutate { rename => { "name" => "[event][dataset]" } }
    }

    if [tags][machine_id] {
      mutate { rename => { "[tags][machine_id]" => "[host][id]" } }
    }
  }

  # For all normalized logs 
  date {
    match => [ "timestamp", "ISO8601", "UNIX", "UNIX_MS" ]
    target => "@timestamp"
  }
}


output {
  opensearch {
    hosts => ["https://${OPENSEARCH_HOST}:9200"]
    index => "logs-%{kafka_topic}-%{+YYYY.MM.dd}"
    user => "admin"
    password => "${OPENSEARCH_PASSWORD}"
    ssl => true
    ssl_certificate_verification => false
  }
}