---
filebeat.inputs:
  - type: filestream # log is deprecated from version 7.16
    id: syslog_logs
    enabled: true
    paths:
      - "/results/fluentd_logs/syslog_output.log.[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].log" 
      #"/fluentd/log/syslog_output.log.[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].log"
        # It does not work with [0-9]{8} sentence, it only works with several [0-9] sentences
    tags: ["syslog_logs"]
    fields:
      kafka_topic: "${FLUENTD_SYSLOG_BASE_TOPIC:syslog_logs}" 
    fields_under_root: true

  - type: filestream #log
    id: systemd_logs
    enabled: true
    paths:
      - "/results/fluentd_logs/systemd_output.log.[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].log"
      #"/fluentd/log/systemd_output.log.[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].log"
        # Example: /fluentd/log/systemd_output.log.20250124.log
    tags: ["systemd_logs"]
    fields:
      kafka_topic: "${FLUENTD_SYSTEMD_BASE_TOPIC:systemd_logs}" 
    fields_under_root: true

  - type: filestream #log
    id: tshark_ndjson_traces
    enabled: true
    paths:
      - "/results/tshark/traces/infile.ndjson" #"/tshark/traces/infile.ndjson"
    tags: ["tshark_ndjson_traces"]
    fields:
      kafka_topic: "${TSHARK_BASE_TOPIC:tshark_traces}" 
    fields_under_root: true
    parsers:
      - ndjson:
          target: ""           # Leave the flat JSON at the root of the network event
          add_error_key: true
    close.reader.on_eof: true              # closes when it finishes reading a file (EOF)
    close.on_state_change.renamed: true    # closes when it detects that the file has been renamed
    clean_removed: true                    # clears the status when the file is no longer present
  
  - type: filestream #log
    id: falco_events
    enabled: true
    paths:
      - "/results/falco/logs/falco_events.json" #"/falco/logs/falco_events.json"
    tags: ["falco_events"]
    fields:
      kafka_topic: "${FALCO_BASE_TOPIC:falco_events}" # Primero "${FALCO_BASE_TOPIC}" solo y luego cuando meta más cambios esto "${FALCO_BASE_TOPIC}_${MACHINE_ID}"
    fields_under_root: true

output.kafka:
  hosts: ["${KAFKA_BOOTSTRAP}"]
  topic: '%{[kafka_topic]}'
  compression: "${FILEBEAT_COMPRESION}" #lz4
  required_acks: "1"
  partition.round_robin.reachable_only: true
  bulk_max_size: "${FILEBEAT_BULK_MAX_SIZE}"
# Filebeat logs by stdout
logging.to_files: false
logging.level: info
