
---
services:
  kafka_robust6g:
    image: apache/kafka:3.9.0
    container_name: kafka_robust6g
    profiles: ["communication_module.kafka"]
    healthcheck:
      test: ["CMD", "nc", "-z", "kafka_robust6g", "29092"]
      interval: 5s
      retries: 15
      start_period: 10s
      timeout: 3s
    environment:
      TZ: "UTC"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_robust6g:9093
      # BROKER for internal connections and EXTERNAL for external connection
      # kafka_robust6g:29092 -> same Docker network
      # host.docker.internal:9092 -> same host, but other network
      # kafka_robust6g-node1.lan:9094 -> other host
      KAFKA_LISTENERS: >
        BROKER://0.0.0.0:29092,
        EXTERNAL_DOCKER://0.0.0.0:9092,
        EXTERNAL_LAN://0.0.0.0:9094,
        CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: >
        BROKER://kafka_robust6g:29092,
        EXTERNAL_DOCKER://host.docker.internal:9092,
        EXTERNAL_LAN://kafka_robust6g-node1.lan:9094,
        CONTROLLER://kafka_robust6g:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        BROKER:PLAINTEXT,
        EXTERNAL_DOCKER:PLAINTEXT,
        EXTERNAL_LAN:PLAINTEXT,
        CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
      KAFKA_NUM_PARTITIONS: "1"

  # === Default retention (APPLIES PER PARTITION - NUM_PARTITIONS = 1) ===
      KAFKA_LOG_RETENTION_MS: "86400000"          # 1 day
      KAFKA_LOG_RETENTION_BYTES: "1073741824"     # 1 GiB (1 * 1024^3)
      KAFKA_LOG_CLEANUP_POLICY: "delete"          # deletion (not only compact)
      KAFKA_LOG_SEGMENT_BYTES: "268435456"        # 256 MiB: rotates more frequently
      KAFKA_LOG_ROLL_MS: "3600000"                # rotated by time if there is little traffic

    ports:
      - "29092:29092"
      - "9092:9092"
      - "9094:9094"

  filebeat:
    image: elastic/filebeat:8.16.2
    container_name: filebeat_robust6g
    profiles: ["communication_module.filebeat"]
    environment:
      - TZ=UTC
    depends_on:
      - kafka_robust6g
    volumes:
      - ${PFD}/Communication_Bus/Configuration_Files/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ${PFD}/Results/fluentd_logs:/fluentd/log:ro
      - ${PFD}/Results/tshark/traces:/tshark/traces:ro
      - ${PFD}/Results/falco/logs:/falco/logs:ro
    restart: unless-stopped
    user: root