# sudo docker compose up -d
# sudo docker exec -it IDCONTAINER bash
---
services:

  flow_module:
    image: flow_module_robust6g:latest
    build:
      context: ${PFD}
      dockerfile: Flow_Module/Docker/Dockerfiles/flow_module.dockerfile
    container_name: flow_module_robust6g
    profiles: ["flow_module.flow_module"]
    restart: unless-stopped
    depends_on:
      kafka_robust6g:
        condition: service_healthy
    environment:
      - TZ=${TZ}
      - KAFKA_BOOTSTRAP=${KAFKA_BOOTSTRAP}
      - KAFKA_ENABLE_AUTO_COMMIT=false
      - FLOW_KAFKA_GROUP=${FLOW_KAFKA_GROUP}
      - TSHARK_BASE_TOPIC=${TSHARK_BASE_TOPIC}
      - CIC_KAFKA_BASE_TOPIC_OUT=${CIC_KAFKA_BASE_TOPIC_OUT}
      - FLOW_PCAP_ROTATE_SIZE_MB=${FLOW_PCAP_ROTATE_SIZE_MB}
      - FLOW_CIC_ROTATE_SIZE_MB=${FLOW_CIC_ROTATE_SIZE_MB}
      - FLOW_ROTATE_TIME_SEC=${FLOW_ROTATE_TIME_SEC}
      - FLOW_PACKET_QUEUE_MAX=${FLOW_PACKET_QUEUE_MAX}
      - FLOW_WRITER_FLUSH_EVERY=${FLOW_WRITER_FLUSH_EVERY}
      - FLOW_WATCHDOG_STALL_SECS=${FLOW_WATCHDOG_STALL_SECS}
      - MONGO_URI=${MONGO_URI}
      - FLOW_KAFKA_CONSUMER_AUTO_OFFSET_RESET=${FLOW_KAFKA_CONSUMER_AUTO_OFFSET_RESET}
      - FLOW_KAFKA_CONSUMER_ENABLE_AUTO_COMMIT=${FLOW_KAFKA_CONSUMER_ENABLE_AUTO_COMMIT}
      - FLOW_KAFKA_CONSUMER_PARTITION_ASSIGNMENT_STRATEGY=${FLOW_KAFKA_CONSUMER_PARTITION_ASSIGNMENT_STRATEGY}
      - FLOW_KAFKA_CONSUMER_ENABLE_PARTITION_EOF=${FLOW_KAFKA_CONSUMER_ENABLE_PARTITION_EOF}
      - FLOW_KAFKA_CONSUMER_ALLOW_AUTO_CREATE_TOPICS=${FLOW_KAFKA_CONSUMER_ALLOW_AUTO_CREATE_TOPICS}
      - FLOW_KAFKA_PRODUCER_LINGER_MS=${FLOW_KAFKA_PRODUCER_LINGER_MS}
      - FLOW_KAFKA_PRODUCER_BATCH_SIZE=${FLOW_KAFKA_PRODUCER_BATCH_SIZE}
      - FLOW_KAFKA_PRODUCER_COMPRESSION=${FLOW_KAFKA_PRODUCER_COMPRESSION}

    extra_hosts:
      - "${KAFKA_LAN_HOSTNAME}:host-gateway"
    volumes:
      - ${PFD}/Results/Flows:/home/Flow_Module/Results/Flows
      - ${PFD}/Results/Traces_Flow_Module:/home/Flow_Module/Scripts/Parsing/PCAP_Files/
